# Generated by Django 5.2.15 on 2026-06-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magicbag',
            options={'ordering': ['-created_at']},
        ),
    ]
