# Generated by Django 5.2.15 on 2026-07-01 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_magicbag_options'),
        ('stores', '0004_useraddress_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='magicbag',
            name='category',
            field=models.CharField(choices=[('VEGETABLES', 'میوه و سبزیجات'), ('SWEETS', 'شیرینی و دسر'), ('FOODS', 'غذاهای آماده'), ('SUPERMARKET', 'سوپرمارکت'), ('RESTAURANT', 'رستوران و فست\u200cفود'), ('BAKERY', 'نان و نانوایی'), ('BEVERAGES', 'نوشیدنی\u200cها'), ('INGREDIENTS', 'مواد اولیه'), ('OTHER', 'سایر')], default='FOODS', max_length=50),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='name',
            field=models.CharField(default='کیسه جادویی', max_length=255),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_bags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magicbag',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_bags', to='stores.store'),
        ),
    ]
