# Generated by Django 5.2.15 on 2026-07-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_magicbag_category_magicbag_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicbag',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='expiry_image',
            field=models.FileField(blank=True, null=True, upload_to='expiry_labels/'),
        ),
        migrations.AddField(
            model_name='magicbag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bags/'),
        ),
    ]
