# Generated by Django 5.2.15 on 2026-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_magicbag_approval_status_magicbag_expiry_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brand', models.TextField(blank=True, null=True)),
                ('category', models.TextField()),
                ('barcode', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(max_length=64)),
                ('source_product_id', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='magicbag',
            name='catalog_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
