# Generated by Django 5.2.15 on 2026-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
