# Generated by Django 5.2.15 on 2026-06-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_useraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
